//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOC
    {
        public int GIOBD { get; set; }
        public int GIOKT { get; set; }
        public Nullable<double> PHI { get; set; }
    }
}
