//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string IDSIM { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual SIM SIM { get; set; }
    }
}
