//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCDT_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string MATS { get; set; }
        public string DIENGIAI { get; set; }
        public Nullable<double> GIATRI { get; set; }
    }
}
